version: '3.8'

services:
  todo-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - todo-database
    env_file:
      - .env
    ports:
      - 3001:3000
      - 35729:35729
    networks:
      - app-network

  todo-rooms:
    build:
      context: ./rooms
      dockerfile: Dockerfile
    depends_on:
      - todo-database
    env_file:
      - .env
    ports:
      - 3002:3000
      - 35730:35729
    networks:
      - app-network

  todo-database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db/db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    

  reverse-proxie:
    build: 
      context: ./reverse-proxie
      dockerfile: Dockerfile
    depends_on:
      - todo-app
      - todo-rooms
    env_file:
      - .env
    ports:
      - "81:80"  # Expose port 80 (HTTP) to the outside world
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
